Felixheidecke reignite
owncloud/calendar pull request #759
Opened 2016-10-21 16:08 UTC by felixheidecke

## Description
Merge changes from external maintainers

## Related Issue

## Motivation and Context
Bringing back maintenance to the calendar.

## How Has This Been Tested?
- [x] TEST: setup new OC: run make on calendar, check if it works in the browser.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@DeepDiver1975 @PVince81

2016-10-21 16:20 UTC, tcitworld requested changes
You'll also need to revert icons changed and newly added screenshots.

2016-10-21 16:20 UTC, tcitworld commented on .travis.yml
> +      env: "DB=mysql CORE_BRANCH=stable10"
Nope.
Also, remove all nc references here.

2016-10-21 16:20 UTC, tcitworld commented on controller/viewcontroller.php
> +		$runningOnNextcloud10OrLater = version_compare($runningOn, '9.1', '>=');
I think this can be kept as is otherwise you'll have trouble rebasing each time.

2016-10-21 16:20 UTC, tcitworld commented on controller/viewcontroller.php
> +		$sendFromAddress = $this->config->getSystemValue('mail_from_address', 'nextcloud');
change

2016-10-21 16:20 UTC, tcitworld commented on js/app/factory/icalFactory.js
> +		root.updatePropertyWithValue('prodid', '-//Nextcloud calendar v' + version);
change me

2016-10-21 16:20 UTC, tcitworld commented on js/app/service/veventService.js
> +		const uri = StringUtility.uid('Nextcloud', 'ics');
change me

2016-10-21 16:20 UTC, tcitworld commented on js/package.json
> +  "homepage": "https://github.com/nextcloud/calendar",
change me (also below)

2016-10-21 16:20 UTC, tcitworld commented on l10n/.tx/config
> +[nextcloud.calendar]
change me

2016-10-21 16:24 UTC, tcitworld commented
Also you can rebase. :-)

2016-10-22 11:28 UTC, jancborchardt commented
@felixheidecke since you’re taking all the improvements made in the original repository at https://github.com/nextcloud/calendar which is maintained by @georgehrke @raghunayyar & @tcitworld, I’m sure they would appreciate if you contribute there as well. :)

2016-10-22 20:53 UTC, DeepDiver1975 commented
> I’m sure they would appreciate if you contribute there as well. :)

Absolutly - just like all ownClouders would appreciate if nextClouders would contribute to core 🙈

2016-10-24 21:14 UTC, jancborchardt commented
@DeepDiver1975 you know very well that the comparison is moot because ownCloud core requires developers to sign a CLA so a company could do whatever it wants with it in the future.
Nextcloud doesn’t do that in the server, nor for any of the apps. That’s a big part of the reason of the fork – just in case it wasn’t clear.

Also lots of Nextclouders contributed to several ownCloud repos for a long time after the fork. You however directly said something along the lines of that you will never contribute to any Nextcloud repo. That’s not what collaboration and appreciation of contribution means, is it?

2016-10-24 21:26 UTC, DeepDiver1975 commented
> That’s a big part of the reason of the fork – just in case it wasn’t clear.

I'll no comment that.

> Also lots of Nextclouders contributed to several ownCloud repos for a long time after the fork.

I want prove for that :see_no_evil: 

> You however directly said something along the lines of that you will never contribute to any Nextcloud repo.

yes - and I have my very personal reasons for that which are know and/or to be discussed in person.

> That’s not what collaboration and appreciation of contribution means, is it?

The whole fork is beyond collaboration - right?

2016-10-24 21:29 UTC, DeepDiver1975 commented
Just to be clear on what is going on here from an owncloud perspective:
- @felixheidecke will maintain calendar
- in a very first step we will sync up the repos
- after that we will continue to develop this app
- nc is welcome to grab changes
- we will continue to grab commits from nextcloud/calendar as well

2016-10-28 08:52 UTC, felixheidecke commented on .travis.yml
> +      env: "DB=mysql CORE_BRANCH=stable10"
Done

2016-10-28 08:52 UTC, felixheidecke commented on controller/viewcontroller.php
> +		$runningOnNextcloud10OrLater = version_compare($runningOn, '9.1', '>=');
Did as you advised.

2016-10-28 09:04 UTC, DeepDiver1975 requested changes

2016-10-28 09:04 UTC, DeepDiver1975 commented on .lgtm
> +pattern = "(?i):shipit:|:\\+1:|LGTM|👍"
kill it - we dont use lgtm boot - thx

2016-10-28 09:04 UTC, DeepDiver1975 commented on .travis.yml
> +    - if [[ "$NIGHTLY" = "TRUE" ]]; then curl --ftp-create-dirs -T build/artifacts/appstore/calendar.tar.gz -u $FTP_LOGIN:$FTP_PW ftp://upload.portknox.de/htdocs/calendar/owncloud_calendar_nightly_bu
kill this - we don't push nightlies to portknox

2016-10-28 09:04 UTC, DeepDiver1975 commented on img/favicon-touch.svg
> -<svg xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" version="1.1" xml:space="preserve" height="128" width="128" enable-background="new 0 0 595.275 311.111"
pngs above should stay dark blue - not sure about the svgs

2016-10-28 09:26 UTC, DeepDiver1975 approved these changes

2016-10-28 09:26 UTC, DeepDiver1975 commented on .lgtm
> -pattern = "(?i):shipit:|:\\+1:|LGTM|👍"
kill the file - not only the line :wink:

2016-10-31 16:05 UTC, felixheidecke commented
Hey guys,

@DeepDiver1975 @tomneedham … I need some thumbs up to merge ;-)

2016-10-31 16:41 UTC, cdamken commented
👍

2016-11-02 09:57 UTC, merged

2016-11-07 10:13 UTC, RealRancor commented
Out of interest, how is the ocsid issue handle here? At https://apps.owncloud.com/content/show.php/Calendar?content=168707 the https://github.com/nextcloud/calendar/ app is published which only has references to NextCloud in the App text and the appinfo.xml.

2016-11-07 11:23 UTC, DeepDiver1975 commented
> Out of interest, how is the ocsid issue handle here? At https://apps.owncloud.com/content/show.php/Calendar?content=168707 the https://github.com/nextcloud/calendar/ app is published which only has references to NextCloud in the App text and the appinfo.xml.

there will soon (I guess) be an isolated app store for nextcloud - no idea how apps are identified there.
the owncloud calendar will be published as 168707