Added byday recurrence feature
owncloud/calendar pull request #918
Opened 2018-05-18 16:16 UTC by Julian1998

Instructions:

1. create a new event
2. click on more...
3. go to repeating
4. create a new recurrence with byday options

Possible scenarios:

1. creating a new event with byday options
2. modifying the current byday options

All events should render correctly even when changing the first day of the week or/and language

All scenarios work fine in Chrome

2018-05-19 09:06 UTC, DeepDiver1975 commented on js/app/controllers/recurrencecontroller.js
> +			if(typeof $scope.properties.rrule.byday === 'undefined') {
angular.isUndefined

2018-05-30 17:11 UTC, DeepDiver1975 requested changes

2018-05-30 17:11 UTC, DeepDiver1975 commented on js/app/controllers/recurrencecontroller.js
> +			if (!angular.isUndefined($scope.properties.rrule.parameters)) {
dont use inverted logic - https://docs.angularjs.org/api/ng/function/angular.isDefined

2018-05-30 17:16 UTC, DeepDiver1975 commented
![bildschirmfoto von 2018-05-30 19-15-35](https://user-images.githubusercontent.com/1005065/40736280-e0e1062e-643d-11e8-8694-90034ec5562f.png)

jslint hates you ;-)

2018-05-30 17:18 UTC, DeepDiver1975 commented
The day picker is not working for me ....

2018-05-30 17:53 UTC, Julian1998 commented
jslint didn't tell me... alright I will have a look at it... Which day picker exactly?

2018-05-30 19:05 UTC, DeepDiver1975 commented
> Which day picker exactly?

the monday, tueseday and so on one .... will show you these days live ...

2018-05-31 16:07 UTC, Julian1998 commented
Seems like jslint didn't build the js sources correctly because of this error. I will fix it and then it should build

2018-06-04 20:24 UTC, DeepDiver1975 commented
@Julian1998 ping

2018-06-07 13:42 UTC, DeepDiver1975 commented
looks like tests are failing 

```
Firefox 60.0.0 (Linux 0.0.0) The SimpleEvent factory should add the repeating information FAILED
	TypeError: newSimpleData.rrule.parameters is undefined in js/app/models/simpleEventModel.js (line 9)
	repeating@js/app/models/simpleEventModel.js:9:32091
	SimpleEvent/iface.patch@js/app/models/simpleEventModel.js:9:34974
	@tests/js/unit/models/simpleEventModelSpec.js:2156:3
	<Jasmine>
Firefox 60.0.0 (Linux 0.0.0): Executed 161 of 377 (1 FAILED) (0 secs / 0 secs)
 (1 FAILED) (0 secs / 0 secs)

2018-06-11 07:59 UTC, DeepDiver1975 approved these changes

2018-06-11 08:14 UTC, merged