Release 1.5.8
owncloud/calendar pull request #921
Opened 2018-06-12 08:47 UTC by DeepDiver1975

2018-06-12 09:00 UTC, DeepDiver1975 commented
[calendar.tar.gz](https://github.com/owncloud/calendar/files/2093329/calendar.tar.gz)

2018-09-02 10:26 UTC, DeepDiver1975 commented
[calendar-1.5.8-rc2.tar.gz](https://github.com/owncloud/calendar/files/2343206/calendar-1.5.8-rc2.tar.gz)

2018-09-12 07:55 UTC, DeepDiver1975 commented
[calendar-1.5.8-rc3.tar.gz](https://github.com/owncloud/calendar/files/2374060/calendar-1.5.8-rc3.tar.gz)

2018-09-12 09:49 UTC, felixheidecke commented
There is no way for me to review this

2018-09-12 10:13 UTC, DeepDiver1975 commented
> There is no way for me to review this

indeed - no idea why you got set .... :see_no_evil:

2018-09-13 14:30 UTC, DeepDiver1975 commented
[calendar-1.6.0-rc1.tar.gz](https://github.com/owncloud/calendar/files/2379720/calendar-1.6.0-rc1.tar.gz)

2018-09-17 07:04 UTC, DeepDiver1975 commented
[calendar-1.6.0-rc2.tar.gz](https://github.com/owncloud/calendar/files/2387571/calendar-1.6.0-rc2.tar.gz)

2018-09-17 10:16 UTC, Julian1998 requested changes
Uncaught (in promise) cancel

Height at simple event editors title input broken

2018-09-19 15:20 UTC, DeepDiver1975 commented
Final tar ball: 
[calendar.tar.gz](https://github.com/owncloud/calendar/files/2397666/calendar.tar.gz)

2018-09-20 08:25 UTC, merged